;;; gruvbox-light-theme.el --- Gruvbox Light theme -*- lexical-binding: t; -*-

(deftheme gruvbox-light "Gruvbox Light with standard (medium) contrast.")

(let ((bg "#fbf1c7")
      (bg1 "#ebdbb2")
      (bg2 "#d5c4a1")
      (fg "#3c3836")
      (gray "#928374")
      (red "#cc241d")
      (green "#98971a")
      (yellow "#d79921")
      (blue "#458588")
      (purple "#b16286")
      (aqua "#689d6a")
      (orange "#d65d0e"))
  (custom-theme-set-faces
   'gruvbox-light
   `(default ((t (:foreground ,fg :background ,bg))))
   `(cursor ((t (:foreground ,bg :background ,fg))))
   `(fringe ((t (:foreground ,gray :background ,bg))))
   `(region ((t (:background ,bg2))))
   `(highlight ((t (:background ,bg1))))
   `(hl-line ((t (:background ,bg1))))
   `(line-number ((t (:foreground ,gray :background ,bg))))
   `(line-number-current-line ((t (:foreground ,orange :background ,bg1 :weight bold))))
   `(mode-line ((t (:foreground ,fg :background ,bg2 :box nil))))
   `(mode-line-inactive ((t (:foreground ,gray :background ,bg1 :box nil))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(success ((t (:foreground ,green :weight bold))))
   `(warning ((t (:foreground ,yellow :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,gray :slant italic))))
   `(font-lock-keyword-face ((t (:foreground ,red :weight bold))))
   `(font-lock-function-name-face ((t (:foreground ,green))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-constant-face ((t (:foreground ,purple))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-builtin-face ((t (:foreground ,orange))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(isearch ((t (:foreground ,bg :background ,orange :weight bold))))
   `(lazy-highlight ((t (:foreground ,fg :background ,bg2))))
   `(show-paren-match ((t (:foreground ,fg :background ,aqua :weight bold))))
   `(show-paren-mismatch ((t (:foreground ,bg :background ,red :weight bold))))
   `(vertico-current ((t (:background ,bg1))))
   `(corfu-current ((t (:foreground ,bg :background ,blue))))
   `(company-tooltip ((t (:foreground ,fg :background ,bg1))))
   `(company-tooltip-selection ((t (:foreground ,bg :background ,blue))))
   `(diff-added ((t (:foreground ,green))))
   `(diff-removed ((t (:foreground ,red))))
   `(diff-changed ((t (:foreground ,yellow))))
   `(magit-diff-added ((t (:foreground ,green))))
   `(magit-diff-removed ((t (:foreground ,red))))
   `(magit-diff-context-highlight ((t (:background ,bg1))))
   `(org-level-1 ((t (:foreground ,red :weight bold :height 1.2))))
   `(org-level-2 ((t (:foreground ,green :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,yellow :weight bold))))
   `(org-level-4 ((t (:foreground ,blue :weight bold))))
   `(org-block ((t (:foreground ,fg :background ,bg1))))
   `(org-code ((t (:foreground ,orange))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green :weight bold))))))

(provide-theme 'gruvbox-light)
;;; gruvbox-light-theme.el ends here
