;;; kanagawa-lotus-theme.el --- Kanagawa Lotus light theme -*- lexical-binding: t; -*-

(deftheme kanagawa-lotus "Light Kanagawa Lotus palette.")

(let ((bg "#f2ecbc") (bg-alt "#e7dba0") (fg "#545464")
      (muted "#716e61") (border "#c9cbd1") (blue "#4d699b")
      (green "#6f894e") (orange "#cc6d00") (yellow "#77713f")
      (red "#c84053") (violet "#766b90") (cyan "#597b75"))
  (custom-theme-set-faces
   'kanagawa-lotus
   `(default ((t (:foreground ,fg :background ,bg))))
   `(cursor ((t (:background ,red))))
   `(fringe ((t (:foreground ,muted :background ,bg))))
   `(region ((t (:background ,border))))
   `(highlight ((t (:background ,bg-alt))))
   `(hl-line ((t (:background ,bg-alt))))
   `(line-number ((t (:foreground ,muted :background ,bg))))
   `(line-number-current-line ((t (:foreground ,orange :background ,bg-alt :weight bold))))
   `(mode-line ((t (:foreground ,fg :background ,bg-alt :box (:line-width 1 :color ,border)))))
   `(mode-line-inactive ((t (:foreground ,muted :background ,bg :box (:line-width 1 :color ,border)))))
   `(doom-modeline-bar ((t (:background ,orange))))
   `(doom-modeline-bar-inactive ((t (:background ,border))))
   `(doom-modeline-buffer-file ((t (:foreground ,blue :weight bold))))
   `(doom-modeline-buffer-modified ((t (:foreground ,red :weight bold))))
   `(doom-modeline-project-dir ((t (:foreground ,green))))
   `(doom-modeline-info ((t (:foreground ,blue))))
   `(doom-modeline-warning ((t (:foreground ,orange))))
   `(doom-modeline-error ((t (:foreground ,red))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(font-lock-comment-face ((t (:foreground ,muted :slant italic))))
   `(font-lock-keyword-face ((t (:foreground ,violet :weight bold))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight bold))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-type-face ((t (:foreground ,green))))
   `(font-lock-constant-face ((t (:foreground ,orange))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(error ((t (:foreground ,red :weight bold))))
   `(warning ((t (:foreground ,orange :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(isearch ((t (:foreground ,bg :background ,orange :weight bold))))
   `(lazy-highlight ((t (:foreground ,fg :background ,border))))
   `(show-paren-match ((t (:foreground ,bg :background ,violet :weight bold))))
   `(vertical-border ((t (:foreground ,border))))
   `(company-tooltip ((t (:foreground ,fg :background ,bg-alt))))
   `(company-tooltip-selection ((t (:foreground ,bg :background ,blue))))
   `(diff-added ((t (:foreground ,green))))
   `(diff-removed ((t (:foreground ,red))))
   `(diff-changed ((t (:foreground ,orange))))
   `(term-color-black ((t (:foreground ,fg))))
   `(term-color-red ((t (:foreground ,red))))
   `(term-color-green ((t (:foreground ,green))))
   `(term-color-yellow ((t (:foreground ,yellow))))
   `(term-color-blue ((t (:foreground ,blue))))
   `(term-color-magenta ((t (:foreground ,violet))))
   `(term-color-cyan ((t (:foreground ,cyan))))
   `(term-color-white ((t (:foreground ,bg))))))

(provide-theme 'kanagawa-lotus)
;;; kanagawa-lotus-theme.el ends here
